VERSION 5.00
Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} Utility_Data 
   Caption         =   "Utility Data"
   ClientHeight    =   12780
   ClientLeft      =   45
   ClientTop       =   375
   ClientWidth     =   14925
   OleObjectBlob   =   "Utility_Data.frx":0000
   ShowModal       =   0   'False
   StartUpPosition =   1  'CenterOwner
End
Attribute VB_Name = "Utility_Data"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Private Sub cmdCancel_Click()
Me.Hide
frmAdmin.Show
End Sub

Private Sub UserForm_QueryClose(Cancel As Integer, CloseMode As Integer)
    If CloseMode = 0 Then
        Cancel = True
        MsgBox "The X is disabled, please use a button on the form.", vbCritical
    End If
End Sub



Private Sub CommandButton1_Click()
Dim TimeandDate As String
Dim Result As Double
Dim Enrollment_ID_ROSA As Double


Enrollment_ID_ROSA = currentEnrollment


Result = Application.Match(Enrollment_ID_ROSA, Sheets("Enrollments").Range("B1", "B" & Range("B" & Rows.Count).End(xlUp).Row), 0)

Sheets("Enrollments").Cells(Result, 12) = Format(ConvertLocalToGMT(Now(), True), "yyyymmdd:hhmmss")


End Sub

End Sub

Private Sub CommandButton2_Click()
Call UserForm_Initialize

End Sub

Private Sub CommandButton3_Click()
Unload Me

End Sub

Private Sub Frame17_Click()

End Sub

Private Sub UserForm_Initialize()
Dim TimeandDate As String
Dim Results As Double
Dim Enrollment_ID_ROSA As String
Dim ColumnHeadings(46) As String
Dim ColumnValues(46) As String
Dim counter As Double

Enrollment_ID_ROSA = currentEnrollment
Results = Application.Match(Enrollment_ID_ROSA, Sheets("Enrollments").Range("B1", "B" & Range("B" & Rows.Count).End(xlUp).Row), 0)

Elec_Apr_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 51)

Elec_Apr_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 52)
Elec_Apr_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 53)
Elec_Apr_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 54)
Elec_Apr_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 55)
Elec_Apr_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 56)
Elec_Apr_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 57)
Elec_Apr_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 58)
Elec_Apr_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 59)
Elec_Apr_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 60)
Elec_Apr_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 61)
Elec_Apr_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 62)
Elec_Apr_Service_Division.Value = Sheets("Enrollments").Cells(Results, 63)
Elec_Apr_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 64)
Elec_Aug_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 65)
Elec_Aug_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 66)
Elec_Aug_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 67)
Elec_Aug_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 68)
Elec_Aug_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 69)
Elec_Aug_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 70)
Elec_Aug_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 71)
Elec_Aug_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 72)
Elec_Aug_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 73)
Elec_Aug_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 74)
Elec_Aug_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 75)
Elec_Aug_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 76)
Elec_Aug_Service_Division.Value = Sheets("Enrollments").Cells(Results, 77)
Elec_Aug_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 78)
Elec_Dec_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 79)
Elec_Dec_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 80)
Elec_Dec_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 81)
Elec_Dec_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 82)
Elec_Dec_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 83)
Elec_Dec_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 84)
Elec_Dec_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 85)
Elec_Dec_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 86)
Elec_Dec_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 87)
Elec_Dec_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 88)
Elec_Dec_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 89)
Elec_Dec_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 90)
Elec_Dec_Service_Division.Value = Sheets("Enrollments").Cells(Results, 91)
Elec_Dec_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 92)
Elec_Feb_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 93)
Elec_Feb_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 94)
Elec_Feb_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 95)
Elec_Feb_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 96)
Elec_Feb_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 97)
Elec_Feb_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 98)
Elec_Feb_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 99)
Elec_Feb_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 100)
Elec_Feb_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 101)
Elec_Feb_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 102)
Elec_Feb_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 103)
Elec_Feb_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 104)
Elec_Feb_Service_Division.Value = Sheets("Enrollments").Cells(Results, 105)
Elec_Feb_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 106)
Elec_Jan_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 107)
Elec_Jan_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 108)
Elec_Jan_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 109)
Elec_Jan_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 110)
Elec_Jan_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 111)
Elec_Jan_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 112)
Elec_Jan_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 113)
Elec_Jan_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 114)
Elec_Jan_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 115)
Elec_Jan_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 116)
Elec_Jan_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 117)
Elec_Jan_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 118)
Elec_Jan_Service_Division.Value = Sheets("Enrollments").Cells(Results, 119)
Elec_Jan_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 120)
Elec_Jul_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 121)
Elec_Jul_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 122)
Elec_Jul_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 123)
Elec_Jul_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 124)
Elec_Jul_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 125)
Elec_Jul_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 126)
Elec_Jul_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 127)
Elec_Jul_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 128)
Elec_Jul_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 129)
Elec_Jul_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 130)
Elec_Jul_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 131)
Elec_Jul_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 132)
Elec_Jul_Service_Division.Value = Sheets("Enrollments").Cells(Results, 133)
Elec_Jul_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 134)
Elec_Jun_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 135)
Elec_Jun_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 136)
Elec_Jun_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 137)
Elec_Jun_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 138)
Elec_Jun_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 139)
Elec_Jun_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 140)
Elec_Jun_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 141)
Elec_Jun_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 142)
Elec_Jun_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 143)
Elec_Jun_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 144)
Elec_Jun_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 145)
Elec_Jun_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 146)
Elec_Jun_Service_Division.Value = Sheets("Enrollments").Cells(Results, 147)
Elec_Jun_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 148)
Elec_Mar_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 149)
Elec_Mar_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 150)
Elec_Mar_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 151)
Elec_Mar_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 152)
Elec_Mar_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 153)
Elec_Mar_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 154)
Elec_Mar_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 155)
Elec_Mar_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 156)
Elec_Mar_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 157)
Elec_Mar_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 158)
Elec_Mar_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 159)
Elec_Mar_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 160)
Elec_Mar_Service_Division.Value = Sheets("Enrollments").Cells(Results, 161)
Elec_Mar_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 162)
Elec_May_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 163)
Elec_May_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 164)
Elec_May_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 165)
Elec_May_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 166)
Elec_May_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 167)
Elec_May_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 168)
Elec_May_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 169)
Elec_May_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 170)
Elec_May_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 171)
Elec_May_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 172)
Elec_May_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 173)
Elec_May_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 174)
Elec_May_Service_Division.Value = Sheets("Enrollments").Cells(Results, 175)
Elec_May_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 176)
Elec_Nov_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 177)
Elec_Nov_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 178)
Elec_Nov_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 179)
Elec_Nov_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 180)
Elec_Nov_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 181)
Elec_Nov_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 182)
Elec_Nov_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 183)
Elec_Nov_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 184)
Elec_Nov_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 185)
Elec_Nov_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 186)
Elec_Nov_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 187)
Elec_Nov_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 188)
Elec_Nov_Service_Division.Value = Sheets("Enrollments").Cells(Results, 189)
Elec_Nov_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 190)
Elec_Oct_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 191)
Elec_Oct_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 192)
Elec_Oct_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 193)
Elec_Oct_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 194)
Elec_Oct_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 195)
Elec_Oct_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 196)
Elec_Oct_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 197)
Elec_Oct_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 198)
Elec_Oct_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 199)
Elec_Oct_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 200)
Elec_Oct_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 201)
Elec_Oct_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 202)
Elec_Oct_Service_Division.Value = Sheets("Enrollments").Cells(Results, 203)
Elec_Oct_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 204)
Elec_Sep_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 205)
Elec_Sep_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 206)
Elec_Sep_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 207)
Elec_Sep_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 208)
Elec_Sep_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 209)
Elec_Sep_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 210)
Elec_Sep_KW_Billed_on_Demand.Value = Sheets("Enrollments").Cells(Results, 211)
Elec_Sep_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 212)
Elec_Sep_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 213)
Elec_Sep_PF_On_Peak.Value = Sheets("Enrollments").Cells(Results, 214)
Elec_Sep_Power_Factor_on_adjustment.Value = Sheets("Enrollments").Cells(Results, 215)
Elec_Sep_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 216)
Elec_Sep_Service_Division.Value = Sheets("Enrollments").Cells(Results, 217)
Elec_Sep_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 218)
Gas_Apr_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 219)
Gas_Apr_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 220)
Gas_Apr_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 221)
Gas_Apr_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 222)
Gas_Apr_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 223)
Gas_Apr_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 224)
Gas_Apr_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 225)
Gas_Apr_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 226)
Gas_Apr_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 227)
Gas_Apr_Service_Division.Value = Sheets("Enrollments").Cells(Results, 228)
Gas_Apr_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 229)
Gas_Aug_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 230)
Gas_Aug_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 231)
Gas_Aug_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 232)
Gas_Aug_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 233)
Gas_Aug_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 234)
Gas_Aug_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 235)
Gas_Aug_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 236)
Gas_Aug_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 237)
Gas_Aug_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 238)
Gas_Aug_Service_Division.Value = Sheets("Enrollments").Cells(Results, 239)
Gas_Aug_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 240)
Gas_Dec_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 241)
Gas_Dec_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 242)
Gas_Dec_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 243)
Gas_Dec_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 244)
Gas_Dec_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 245)
Gas_Dec_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 246)
Gas_Dec_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 247)
Gas_Dec_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 248)
Gas_Dec_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 249)
Gas_Dec_Service_Division.Value = Sheets("Enrollments").Cells(Results, 250)
Gas_Dec_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 251)
Gas_Feb_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 252)
Gas_Feb_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 253)
Gas_Feb_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 254)
Gas_Feb_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 255)
Gas_Feb_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 256)
Gas_Feb_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 257)
Gas_Feb_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 258)
Gas_Feb_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 259)
Gas_Feb_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 260)
Gas_Feb_Service_Division.Value = Sheets("Enrollments").Cells(Results, 261)
Gas_Feb_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 262)
Gas_Jan_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 263)
Gas_Jan_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 264)
Gas_Jan_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 265)
Gas_Jan_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 266)
Gas_Jan_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 267)
Gas_Jan_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 268)
Gas_Jan_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 269)
Gas_Jan_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 270)
Gas_Jan_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 271)
Gas_Jan_Service_Division.Value = Sheets("Enrollments").Cells(Results, 272)
Gas_Jan_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 273)
Gas_Jul_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 274)
Gas_Jul_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 275)
Gas_Jul_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 276)
Gas_Jul_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 277)
Gas_Jul_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 278)
Gas_Jul_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 279)
Gas_Jul_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 280)
Gas_Jul_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 281)
Gas_Jul_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 282)
Gas_Jul_Service_Division.Value = Sheets("Enrollments").Cells(Results, 283)
Gas_Jul_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 284)
Gas_Jun_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 285)
Gas_Jun_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 286)
Gas_Jun_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 287)
Gas_Jun_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 288)
Gas_Jun_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 289)
Gas_Jun_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 290)
Gas_Jun_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 291)
Gas_Jun_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 292)
Gas_Jun_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 293)
Gas_Jun_Service_Division.Value = Sheets("Enrollments").Cells(Results, 294)
Gas_Jun_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 295)
Gas_Mar_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 296)
Gas_Mar_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 297)
Gas_Mar_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 298)
Gas_Mar_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 299)
Gas_Mar_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 300)
Gas_Mar_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 301)
Gas_Mar_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 302)
Gas_Mar_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 303)
Gas_Mar_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 304)
Gas_Mar_Service_Division.Value = Sheets("Enrollments").Cells(Results, 305)
Gas_Mar_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 306)
Gas_May_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 307)
Gas_May_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 308)
Gas_May_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 309)
Gas_May_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 310)
Gas_May_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 311)
Gas_May_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 312)
Gas_May_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 313)
Gas_May_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 314)
Gas_May_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 315)
Gas_May_Service_Division.Value = Sheets("Enrollments").Cells(Results, 316)
Gas_May_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 317)
Gas_Nov_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 318)
Gas_Nov_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 319)
Gas_Nov_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 320)
Gas_Nov_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 321)
Gas_Nov_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 322)
Gas_Nov_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 323)
Gas_Nov_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 324)
Gas_Nov_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 325)
Gas_Nov_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 326)
Gas_Nov_Service_Division.Value = Sheets("Enrollments").Cells(Results, 327)
Gas_Nov_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 328)
Gas_Oct_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 329)
Gas_Oct_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 330)
Gas_Oct_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 331)
Gas_Oct_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 332)
Gas_Oct_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 333)
Gas_Oct_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 334)
Gas_Oct_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 335)
Gas_Oct_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 336)
Gas_Oct_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 337)
Gas_Oct_Service_Division.Value = Sheets("Enrollments").Cells(Results, 338)
Gas_Oct_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 339)
Gas_Sep_Average_Temperature.Value = Sheets("Enrollments").Cells(Results, 340)
Gas_Sep_Billed_Amount.Value = Sheets("Enrollments").Cells(Results, 341)
Gas_Sep_Billing_Date.Value = Sheets("Enrollments").Cells(Results, 342)
Gas_Sep_Cooling_degree_days.Value = Sheets("Enrollments").Cells(Results, 343)
Gas_Sep_Energy_Consumption.Value = Sheets("Enrollments").Cells(Results, 344)
Gas_Sep_Heating_degree_days.Value = Sheets("Enrollments").Cells(Results, 345)
Gas_Sep_Meter_Number.Value = Sheets("Enrollments").Cells(Results, 346)
Gas_Sep_No_of_billing_days.Value = Sheets("Enrollments").Cells(Results, 347)
Gas_Sep_Rate_Category_Text.Value = Sheets("Enrollments").Cells(Results, 348)
Gas_Sep_Service_Division.Value = Sheets("Enrollments").Cells(Results, 349)
Gas_Sep_Taxes_and_Fees.Value = Sheets("Enrollments").Cells(Results, 350)

'Sheets("Enrollments").Cells(Results, 12) = Format(ConvertLocalToGMT(Now(), True), "yyyymmdd:hhmmss")


End Sub
